application: fb-post-planner-10
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static/css/
  static_dir: static/css
  mime_type: "text/css"
  
- url: /static
  static_dir: static

- url: /.*
  script: main.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest